var i;
$(document).ready(function(){
  $('.analysis__btn').click(function(){
    $('.overlay--analyist').fadeIn(500);
  });
  $('.planning__btn').click(function(){
    $('.overlay--planning').fadeIn(500);
  });
  $('.strategy__btn').click(function(){
    $('.overlay--strategy').fadeIn(500);
  });
  $('.messaging__btn').click(function(){
    $('.overlay--messaging').fadeIn(500);
  });
  $('.overlay').click(function(){
    $(this).fadeOut(500);
  });
  
// Grid BS  
$('.grid1').click(function(){
  $('.overlay--grid1').fadeIn(500);
});
$('.grid2').click(function(){
  $('.overlay--grid2').fadeIn(500);
});
$('.grid3').click(function(){
  $('.overlay--grid3').fadeIn(500);
});
$('.grid4').click(function(){
  $('.overlay--grid4').fadeIn(500);
});
$('.grid5').click(function(){
  $('.overlay--grid5').fadeIn(500);
});
$('.grid6').click(function(){
  $('.overlay--grid6').fadeIn(500);
});
$('.grid7').click(function(){
  $('.overlay--grid7').fadeIn(500);
});
$('.grid8').click(function(){
  $('.overlay--grid8').fadeIn(500);
});
$('.grid9').click(function(){
  $('.overlay--grid9').fadeIn(500);
});
});
